development:
  adapter: postgresql
  database: scuclasses_development
  host: localhost

test:
  adapter: postgresql
  database: scuclasses_test
  username: postgres
  password: admin
  encoding: UTF8
  pool: 5

production:
  adapter: postgresql
  database: scuclasses_production
  encoding: UTF8
  pool: 5
